name: Output Event Details on "issues"
on:
  issues:
    types: [opened, edited, closed]
jobs:
  output-event-details:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJson(github.event) }}"